#!/bin/bash

cd $PGDATA
mkdir tablespaces
chown -R postgres:postgres tablespaces
chmod 777 tablespaces

cd $HOME

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    
    CREATE DATABASE $LONG_APP_NAME
        WITH OWNER = postgres
        ENCODING = 'UTF8'
        TABLESPACE = pg_default
        LC_COLLATE = 'en_US.utf8'
        LC_CTYPE = 'en_US.utf8'
        CONNECTION LIMIT = -1;

    ALTER DATABASE $LONG_APP_NAME SET client_encoding='UTF8';

    CREATE ROLE $LONG_APP_NAME LOGIN
    ENCRYPTED PASSWORD '$LONG_APP_NAME'
    NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

    CREATE ROLE www_$LONG_APP_NAME LOGIN
    ENCRYPTED PASSWORD 'www_$LONG_APP_NAME'
    NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

    CREATE TABLESPACE $LONG_APP_NAME
    owner $LONG_APP_NAME
    LOCATION '$PGTABLESPACES';
   
    ALTER ROLE $LONG_APP_NAME set default_tablespace=$LONG_APP_NAME;

    ALTER DATABASE $LONG_APP_NAME OWNER to $LONG_APP_NAME;

EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$LONG_APP_NAME" <<-EOSQL
    
    CREATE SCHEMA $LONG_APP_NAME AUTHORIZATION $LONG_APP_NAME;

    GRANT USAGE ON SCHEMA $LONG_APP_NAME to www_$LONG_APP_NAME;
    
    ALTER ROLE www_$LONG_APP_NAME SET search_path=$LONG_APP_NAME;

EOSQL