version: "3"

services:
  db:
    image: postgresql:12
    ports:
      -"5432:5432"
    environment:
      - POSTGRES_PASSWORD:$PG_PASSWORD
      - LONG_APP_NAME:$LONG_APP_NAME
    volumes:
      - data:/var/lib/postgresql/data
      - tablespace:/var/lib/postgresql/tablespaces
volumes:
    data:$DATA_PATH
    tablespace:$TABLESPACE_PATH
